name: flutter_news
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:

  sdk: ">=2.16.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 屏幕适配
  flutter_screenutil: ^5.5.4

  # toast
  fluttertoast: ^8.0.9

  #http
  dio: ^4.0.6
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.0.0

  # storage
  shared_preferences: ^2.0.15

  # sha
  crypto: ^3.0.2

  # ui
  flutter_easyrefresh: ^2.2.2

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
